[project]
name = "ducklake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.54",
    "duckdb>=1.4.4",
    "ipykernel>=7.2.0",
    "pins[aws]>=0.9.1",
    "pyarrow>=19.0.0",
]
